import { V, group, STEAM_VARS, type GameTemplate } from "./types";
import { steamInstallScript } from "./steamcmd";

// ARK: Survival Evolved. Settings are split across two ini files:
//   GameUserSettings.ini — [ServerSettings] + [SessionSettings]
//   Game.ini             — [/script/shootergame.shootergamemode]
export const ark: GameTemplate = {
  slug: "ark",
  name: "ARK: Survival Evolved",
  engine: "Unreal Engine 4",
  defaultPort: 7777,
  steamAppId: "376030",
  iconEmoji: "🦖",
  supportsIpv6: false,
  category: "Survival",
  description: "Dinosaur survival sandbox",
  estimatedSize: "~20 GB",
  variables: [
    ...STEAM_VARS,

    ...group("Session", [
      V("Map", "MAP", "Map loaded on start", "TheIsland", {
        required: false, type: "select",
        enum_values: {
          TheIsland: "The Island", TheCenter: "The Center", ScorchedEarth_P: "Scorched Earth",
          Ragnarok: "Ragnarok", Aberration_P: "Aberration", Extinction: "Extinction",
          Valguero_P: "Valguero", Genesis: "Genesis Part 1", CrystalIsles: "Crystal Isles",
          Gen2: "Genesis Part 2", LostIsland: "Lost Island", Fjordur: "Fjordur",
        },
      }),
      V("Server Password", "SERVER_PASSWORD", "Password required to join, empty = public", "", { required: false, type: "password" }),
      V("Admin Password", "ADMIN_PASSWORD", "Password for the in-game admin console — always set this", "", { required: false, type: "password" }),
      V("Spectator Password", "SPECTATOR_PASSWORD", "Password granting spectator mode", "", { required: false, type: "password" }),
      V("Message Of The Day", "MOTD", "Message shown to players on join", "Welcome!", { required: false }),
      V("MOTD Duration", "MOTD_DURATION", "Seconds the MOTD stays on screen", "20", {
        required: false, type: "number", min_value: 1, max_value: 300,
      }),
      V("RCON Enabled", "RCON_ENABLED", "Enable the RCON listener", "true", { required: false, type: "boolean" }),
      V("RCON Port", "RCON_PORT", "Port RCON binds to", "27020", {
        required: false, type: "number", min_value: 1, max_value: 65535,
      }),
    ]),

    ...group("Rates", [
      V("XP Multiplier", "XP_MULTIPLIER", "Experience gain multiplier", "1.0", { required: false, type: "float", min_value: 0.01, max_value: 1000 }),
      V("Taming Speed", "TAMING_SPEED_MULTIPLIER", "Taming speed multiplier — higher tames faster", "1.0", { required: false, type: "float", min_value: 0.01, max_value: 1000 }),
      V("Harvest Amount", "HARVEST_AMOUNT_MULTIPLIER", "Resources gained per harvest action", "1.0", { required: false, type: "float", min_value: 0.01, max_value: 1000 }),
      V("Harvest Health", "HARVEST_HEALTH_MULTIPLIER", "Health of harvestable objects — higher yields more per node", "1.0", { required: false, type: "float", min_value: 0.01, max_value: 1000 }),
      V("Resource Respawn Interval", "RESOURCES_RESPAWN_PERIOD_MULTIPLIER", "Lower respawns resource nodes faster", "1.0", { required: false, type: "float", min_value: 0.01, max_value: 100 }),
      V("Mating Interval", "MATING_INTERVAL_MULTIPLIER", "Cooldown between breeding — lower breeds faster", "1.0", { required: false, type: "float", min_value: 0.01, max_value: 100 }),
      V("Egg Hatch Speed", "EGG_HATCH_SPEED_MULTIPLIER", "Egg incubation speed", "1.0", { required: false, type: "float", min_value: 0.01, max_value: 1000 }),
      V("Baby Mature Speed", "BABY_MATURE_SPEED_MULTIPLIER", "Baby growth speed", "1.0", { required: false, type: "float", min_value: 0.01, max_value: 1000 }),
      V("Baby Food Consumption", "BABY_FOOD_CONSUMPTION_SPEED_MULTIPLIER", "How fast babies eat", "1.0", { required: false, type: "float", min_value: 0.01, max_value: 100 }),
      V("Day Cycle Speed", "DAY_CYCLE_SPEED_SCALE", "Overall day/night cycle speed", "1.0", { required: false, type: "float", min_value: 0.01, max_value: 100 }),
      V("Day Time Speed", "DAY_TIME_SPEED_SCALE", "Daytime length multiplier", "1.0", { required: false, type: "float", min_value: 0.01, max_value: 100 }),
      V("Night Time Speed", "NIGHT_TIME_SPEED_SCALE", "Nighttime length multiplier", "1.0", { required: false, type: "float", min_value: 0.01, max_value: 100 }),
      V("Crop Growth Speed", "CROP_GROWTH_SPEED_MULTIPLIER", "Crop plot growth speed", "1.0", { required: false, type: "float", min_value: 0.01, max_value: 100 }),
      V("Crop Decay Speed", "CROP_DECAY_SPEED_MULTIPLIER", "How fast crops spoil", "1.0", { required: false, type: "float", min_value: 0.01, max_value: 100 }),
    ]),

    ...group("Combat & Damage", [
      V("Player Damage", "PLAYER_DAMAGE_MULTIPLIER", "Damage players deal", "1.0", { required: false, type: "float", min_value: 0.01, max_value: 100 }),
      V("Player Resistance", "PLAYER_RESISTANCE_MULTIPLIER", "Damage players take — lower is tougher", "1.0", { required: false, type: "float", min_value: 0.01, max_value: 100 }),
      V("Dino Damage", "DINO_DAMAGE_MULTIPLIER", "Damage wild dinos deal", "1.0", { required: false, type: "float", min_value: 0.01, max_value: 100 }),
      V("Dino Resistance", "DINO_RESISTANCE_MULTIPLIER", "Damage wild dinos take", "1.0", { required: false, type: "float", min_value: 0.01, max_value: 100 }),
      V("Tamed Dino Damage", "TAMED_DINO_DAMAGE_MULTIPLIER", "Damage tamed dinos deal", "1.0", { required: false, type: "float", min_value: 0.01, max_value: 100 }),
      V("Tamed Dino Resistance", "TAMED_DINO_RESISTANCE_MULTIPLIER", "Damage tamed dinos take", "1.0", { required: false, type: "float", min_value: 0.01, max_value: 100 }),
      V("Structure Damage", "STRUCTURE_DAMAGE_MULTIPLIER", "Damage dealt to structures", "1.0", { required: false, type: "float", min_value: 0.01, max_value: 100 }),
      V("Structure Resistance", "STRUCTURE_RESISTANCE_MULTIPLIER", "Damage structures take", "1.0", { required: false, type: "float", min_value: 0.01, max_value: 100 }),
      V("Difficulty Offset", "DIFFICULTY_OFFSET", "0-1 scale controlling wild dino levels", "1.0", { required: false, type: "float", min_value: 0, max_value: 1 }),
      V("Override Official Difficulty", "OVERRIDE_OFFICIAL_DIFFICULTY", "Max wild dino level tier (5.0 = level 150)", "5.0", { required: false, type: "float", min_value: 0, max_value: 50 }),
      V("Enable PvP", "SERVER_PVE", "Set false for PvP, true for PvE only", "false", { required: false, type: "boolean" }),
      V("Enable PvP Structure Decay", "PVP_STRUCTURE_DECAY", "Structures decay on PvP servers", "false", { required: false, type: "boolean" }),
      V("Disable Friendly Fire", "PREVENT_FRIENDLY_FIRE", "Block damage between tribe members", "false", { required: false, type: "boolean" }),
      V("Allow Cave Building (PvE)", "ALLOW_CAVE_BUILDING_PVE", "Permit building inside caves on PvE", "false", { required: false, type: "boolean" }),
    ]),

    ...group("Player & Tribe", [
      V("Player Water Drain", "PLAYER_CHARACTER_WATER_DRAIN", "How fast players get thirsty", "1.0", { required: false, type: "float", min_value: 0.01, max_value: 100 }),
      V("Player Food Drain", "PLAYER_CHARACTER_FOOD_DRAIN", "How fast players get hungry", "1.0", { required: false, type: "float", min_value: 0.01, max_value: 100 }),
      V("Player Stamina Drain", "PLAYER_CHARACTER_STAMINA_DRAIN", "How fast stamina depletes", "1.0", { required: false, type: "float", min_value: 0.01, max_value: 100 }),
      V("Player Health Recovery", "PLAYER_CHARACTER_HEALTH_RECOVERY", "Player health regeneration rate", "1.0", { required: false, type: "float", min_value: 0.01, max_value: 100 }),
      V("Max Tribe Size", "MAX_NUMBERS_OF_PLAYERS_IN_TRIBE", "Players allowed per tribe, 0 = unlimited", "0", {
        required: false, type: "number", min_value: 0, max_value: 500,
      }),
      V("Tribe Name Change Cooldown", "TRIBE_NAME_CHANGE_COOLDOWN", "Minutes before a tribe can rename again", "15", {
        required: false, type: "number", min_value: 0, max_value: 10080,
      }),
      V("Allow Third Person", "ALLOW_THIRD_PERSON_PLAYER", "Allow the third-person camera", "true", { required: false, type: "boolean" }),
      V("Show Map Player Location", "SHOW_MAP_PLAYER_LOCATION", "Show player coordinates on the map", "true", { required: false, type: "boolean" }),
      V("Global Voice Chat", "GLOBAL_VOICE_CHAT", "Voice chat is heard server-wide", "false", { required: false, type: "boolean" }),
      V("Proximity Chat", "PROXIMITY_CHAT", "Restrict text chat to nearby players", "false", { required: false, type: "boolean" }),
      V("No Tribute Downloads", "NO_TRIBUTE_DOWNLOADS", "Block downloading characters and items from other servers", "false", { required: false, type: "boolean" }),
      V("Allow Flyer Carry PvE", "ALLOW_FLYER_CARRY_PVE", "Flyers can pick up wild dinos on PvE", "false", { required: false, type: "boolean" }),
    ]),

    ...group("Structures & Dinos", [
      V("Max Structures In Range", "THE_MAX_STRUCTURES_IN_RANGE", "Structure cap within a build radius", "10500", {
        required: false, type: "number", min_value: 100, max_value: 100000,
      }),
      V("Structure Pickup Time", "STRUCTURE_PICKUP_TIME_AFTER_PLACEMENT", "Seconds a structure may be picked back up", "30", {
        required: false, type: "number", min_value: 0, max_value: 3600,
      }),
      V("Always Allow Structure Pickup", "ALWAYS_ALLOW_STRUCTURE_PICKUP", "Ignore the pickup timer entirely", "false", { required: false, type: "boolean" }),
      V("Dino Count Multiplier", "DINO_COUNT_MULTIPLIER", "Wild dino spawn density", "1.0", { required: false, type: "float", min_value: 0.01, max_value: 100 }),
      V("Max Tamed Dinos", "MAX_TAMED_DINOS", "Server-wide tamed dino cap", "5000", {
        required: false, type: "number", min_value: 1, max_value: 100000,
      }),
      V("Personal Tamed Dino Cap", "PERSONAL_TAMED_DINOS_CAP", "Tamed dino cap per tribe, 0 = unlimited", "0", {
        required: false, type: "number", min_value: 0, max_value: 10000,
      }),
      V("Allow Raid Dino Feeding", "ALLOW_RAID_DINO_FEEDING", "Allow feeding titanosaurs and other raid dinos", "false", { required: false, type: "boolean" }),
      V("Disable Dino Decay PvE", "DISABLE_DINO_DECAY_PVE", "Tamed dinos never decay on PvE", "false", { required: false, type: "boolean" }),
      V("Auto Destroy Structures", "AUTO_DESTROY_OLD_STRUCTURES_MULTIPLIER", "Days before abandoned structures auto-destroy, 0 = off", "0", { required: false, type: "float", min_value: 0, max_value: 100 }),
    ]),

    ...group("Items & Inventory", [
      V("Item Stack Size Multiplier", "ITEM_STACK_SIZE_MULTIPLIER", "Global stack size multiplier", "1.0", { required: false, type: "float", min_value: 0.01, max_value: 1000 }),
      V("Player Weight Multiplier", "PLAYER_CHARACTER_WEIGHT_MULTIPLIER", "Player carry capacity multiplier", "1.0", { required: false, type: "float", min_value: 0.01, max_value: 1000 }),
      V("Supply Crate Loot Quality", "SUPPLY_CRATE_LOOT_QUALITY_MULTIPLIER", "Loot quality from supply drops", "1.0", { required: false, type: "float", min_value: 0.01, max_value: 100 }),
      V("Fishing Loot Quality", "FISHING_LOOT_QUALITY_MULTIPLIER", "Loot quality from fishing", "1.0", { required: false, type: "float", min_value: 0.01, max_value: 100 }),
      V("Clamp Item Stats", "ITEM_STAT_CLAMPS", "Clamp item stats to prevent duped super-items", "false", { required: false, type: "boolean" }),
      V("Global Item Decomposition", "GLOBAL_ITEM_DECOMPOSITION_TIME_MULTIPLIER", "How fast dropped items despawn", "1.0", { required: false, type: "float", min_value: 0.01, max_value: 100 }),
      V("Corpse Decomposition", "GLOBAL_CORPSE_DECOMPOSITION_TIME_MULTIPLIER", "How fast corpses despawn", "1.0", { required: false, type: "float", min_value: 0.01, max_value: 100 }),
    ]),

    ...group("Server Behaviour", [
      V("Auto Save Period", "AUTO_SAVE_PERIOD_MINUTES", "Minutes between world saves", "15", { required: false, type: "float", min_value: 1, max_value: 240 }),
      V("Kick Idle Players Period", "KICK_IDLE_PLAYERS_PERIOD", "Seconds before an idle player is kicked", "3600", {
        required: false, type: "number", min_value: 60, max_value: 86400,
      }),
      V("Enable Idle Player Kick", "ENABLE_IDLE_PLAYER_KICK", "Kick players who go idle", "false", { required: false, type: "boolean" }),
      V("Allow Anyone Baby Imprint", "ALLOW_ANYONE_BABY_IMPRINT_CUDDLE", "Any tribe member can imprint on a baby", "true", { required: false, type: "boolean" }),
      V("Baby Imprint Stat Scale", "BABY_IMPRINTING_STAT_SCALE_MULTIPLIER", "Stat bonus per imprint percentage", "1.0", { required: false, type: "float", min_value: 0, max_value: 100 }),
      V("Structure Prevent Resource Radius", "STRUCTURE_PREVENT_RESOURCE_RADIUS_MULTIPLIER", "Radius where structures block resource respawn", "1.0", { required: false, type: "float", min_value: 0.01, max_value: 100 }),
      V("Ban List URL", "BAN_LIST_URL", "URL of a shared ban list", "", { required: false }),
      V("Force Respawn Dinos", "FORCE_RESPAWN_DINOS", "Wipe and respawn all wild dinos on next boot", "false", { required: false, type: "boolean" }),
      V("Prevent Download Survivors", "PREVENT_DOWNLOAD_SURVIVORS", "Block survivor uploads from other servers", "false", { required: false, type: "boolean" }),
      V("Prevent Download Items", "PREVENT_DOWNLOAD_ITEMS", "Block item uploads from other servers", "false", { required: false, type: "boolean" }),
      V("Prevent Download Dinos", "PREVENT_DOWNLOAD_DINOS", "Block dino uploads from other servers", "false", { required: false, type: "boolean" }),
    ]),
  ],

  installScript: steamInstallScript({
    appId: "376030",
    name: "ARK: Survival Evolved",
    post: `## ARK reads its ini files from the Saved config directory
mkdir -p "$INSTALL_DIR/ShooterGame/Saved/Config/LinuxServer"`,
  }),

  startCommand: `cd {{INSTALL_PATH}}/ShooterGame/Binaries/Linux && ./ShooterGameServer "{{MAP}}?listen?SessionName={{SERVER_NAME}}?Port={{PORT}}?QueryPort={{QUERY_PORT}}?RCONPort={{RCON_PORT}}?RCONEnabled={{RCON_ENABLED}}?ServerPassword={{SERVER_PASSWORD}}?ServerAdminPassword={{ADMIN_PASSWORD}}?MaxPlayers={{MAX_PLAYERS}}" -server -log -NoBattlEye`,
  stopCommand: "quit",
  configFiles: {
    "ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini": "GameUserSettings.ini",
    "ShooterGame/Saved/Config/LinuxServer/Game.ini": "Game.ini",
  },
  defaultConfig: {
    __files: {
      "ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini": {
        __gsm_format: "ini",
        ServerSettings: {
          SessionName: "{{SERVER_NAME}}",
          ServerPassword: "{{SERVER_PASSWORD}}",
          ServerAdminPassword: "{{ADMIN_PASSWORD}}",
          SpectatorPassword: "{{SPECTATOR_PASSWORD}}",
          RCONEnabled: "{{RCON_ENABLED}}",
          RCONPort: "{{RCON_PORT}}",
          MOTD: "{{MOTD}}",
          MessageOfTheDayDuration: "{{MOTD_DURATION}}",
          XPMultiplier: "{{XP_MULTIPLIER}}",
          TamingSpeedMultiplier: "{{TAMING_SPEED_MULTIPLIER}}",
          HarvestAmountMultiplier: "{{HARVEST_AMOUNT_MULTIPLIER}}",
          HarvestHealthMultiplier: "{{HARVEST_HEALTH_MULTIPLIER}}",
          ResourcesRespawnPeriodMultiplier: "{{RESOURCES_RESPAWN_PERIOD_MULTIPLIER}}",
          DayCycleSpeedScale: "{{DAY_CYCLE_SPEED_SCALE}}",
          DayTimeSpeedScale: "{{DAY_TIME_SPEED_SCALE}}",
          NightTimeSpeedScale: "{{NIGHT_TIME_SPEED_SCALE}}",
          CropGrowthSpeedMultiplier: "{{CROP_GROWTH_SPEED_MULTIPLIER}}",
          CropDecaySpeedMultiplier: "{{CROP_DECAY_SPEED_MULTIPLIER}}",
          PlayerDamageMultiplier: "{{PLAYER_DAMAGE_MULTIPLIER}}",
          PlayerResistanceMultiplier: "{{PLAYER_RESISTANCE_MULTIPLIER}}",
          DinoDamageMultiplier: "{{DINO_DAMAGE_MULTIPLIER}}",
          DinoResistanceMultiplier: "{{DINO_RESISTANCE_MULTIPLIER}}",
          TamedDinoDamageMultiplier: "{{TAMED_DINO_DAMAGE_MULTIPLIER}}",
          TamedDinoResistanceMultiplier: "{{TAMED_DINO_RESISTANCE_MULTIPLIER}}",
          StructureDamageMultiplier: "{{STRUCTURE_DAMAGE_MULTIPLIER}}",
          StructureResistanceMultiplier: "{{STRUCTURE_RESISTANCE_MULTIPLIER}}",
          DifficultyOffset: "{{DIFFICULTY_OFFSET}}",
          OverrideOfficialDifficulty: "{{OVERRIDE_OFFICIAL_DIFFICULTY}}",
          serverPVE: "{{SERVER_PVE}}",
          PvPStructureDecay: "{{PVP_STRUCTURE_DECAY}}",
          PreventTribeAlliances: "false",
          bPvEDisableFriendlyFire: "{{PREVENT_FRIENDLY_FIRE}}",
          bAllowCaveBuildingPvE: "{{ALLOW_CAVE_BUILDING_PVE}}",
          PlayerCharacterWaterDrainMultiplier: "{{PLAYER_CHARACTER_WATER_DRAIN}}",
          PlayerCharacterFoodDrainMultiplier: "{{PLAYER_CHARACTER_FOOD_DRAIN}}",
          PlayerCharacterStaminaDrainMultiplier: "{{PLAYER_CHARACTER_STAMINA_DRAIN}}",
          PlayerCharacterHealthRecoveryMultiplier: "{{PLAYER_CHARACTER_HEALTH_RECOVERY}}",
          MaxNumbersofPlayersInTribe: "{{MAX_NUMBERS_OF_PLAYERS_IN_TRIBE}}",
          TribeNameChangeCooldown: "{{TRIBE_NAME_CHANGE_COOLDOWN}}",
          AllowThirdPersonPlayer: "{{ALLOW_THIRD_PERSON_PLAYER}}",
          ShowMapPlayerLocation: "{{SHOW_MAP_PLAYER_LOCATION}}",
          globalVoiceChat: "{{GLOBAL_VOICE_CHAT}}",
          proximityChat: "{{PROXIMITY_CHAT}}",
          noTributeDownloads: "{{NO_TRIBUTE_DOWNLOADS}}",
          PreventDownloadSurvivors: "{{PREVENT_DOWNLOAD_SURVIVORS}}",
          PreventDownloadItems: "{{PREVENT_DOWNLOAD_ITEMS}}",
          PreventDownloadDinos: "{{PREVENT_DOWNLOAD_DINOS}}",
          AllowFlyerCarryPvE: "{{ALLOW_FLYER_CARRY_PVE}}",
          TheMaxStructuresInRange: "{{THE_MAX_STRUCTURES_IN_RANGE}}",
          StructurePickupTimeAfterPlacement: "{{STRUCTURE_PICKUP_TIME_AFTER_PLACEMENT}}",
          AlwaysAllowStructurePickup: "{{ALWAYS_ALLOW_STRUCTURE_PICKUP}}",
          StructurePreventResourceRadiusMultiplier: "{{STRUCTURE_PREVENT_RESOURCE_RADIUS_MULTIPLIER}}",
          DinoCountMultiplier: "{{DINO_COUNT_MULTIPLIER}}",
          MaxTamedDinos: "{{MAX_TAMED_DINOS}}",
          PersonalTamedDinosSaddleStructureCost: "0",
          AllowRaidDinoFeeding: "{{ALLOW_RAID_DINO_FEEDING}}",
          DisableDinoDecayPvE: "{{DISABLE_DINO_DECAY_PVE}}",
          AutoDestroyOldStructuresMultiplier: "{{AUTO_DESTROY_OLD_STRUCTURES_MULTIPLIER}}",
          ItemStackSizeMultiplier: "{{ITEM_STACK_SIZE_MULTIPLIER}}",
          PlayerCharacterWeightMultiplier: "{{PLAYER_CHARACTER_WEIGHT_MULTIPLIER}}",
          SupplyCrateLootQualityMultiplier: "{{SUPPLY_CRATE_LOOT_QUALITY_MULTIPLIER}}",
          FishingLootQualityMultiplier: "{{FISHING_LOOT_QUALITY_MULTIPLIER}}",
          ClampItemStats: "{{ITEM_STAT_CLAMPS}}",
          GlobalItemDecompositionTimeMultiplier: "{{GLOBAL_ITEM_DECOMPOSITION_TIME_MULTIPLIER}}",
          GlobalCorpseDecompositionTimeMultiplier: "{{GLOBAL_CORPSE_DECOMPOSITION_TIME_MULTIPLIER}}",
          AutoSavePeriodMinutes: "{{AUTO_SAVE_PERIOD_MINUTES}}",
          KickIdlePlayersPeriod: "{{KICK_IDLE_PLAYERS_PERIOD}}",
          EnableIdlePlayerKick: "{{ENABLE_IDLE_PLAYER_KICK}}",
          MatingIntervalMultiplier: "{{MATING_INTERVAL_MULTIPLIER}}",
          EggHatchSpeedMultiplier: "{{EGG_HATCH_SPEED_MULTIPLIER}}",
          BabyMatureSpeedMultiplier: "{{BABY_MATURE_SPEED_MULTIPLIER}}",
          BabyFoodConsumptionSpeedMultiplier: "{{BABY_FOOD_CONSUMPTION_SPEED_MULTIPLIER}}",
          BabyImprintingStatScaleMultiplier: "{{BABY_IMPRINTING_STAT_SCALE_MULTIPLIER}}",
          AllowAnyoneBabyImprintCuddle: "{{ALLOW_ANYONE_BABY_IMPRINT_CUDDLE}}",
          ForceRespawnDinos: "{{FORCE_RESPAWN_DINOS}}",
          BanListURL: "{{BAN_LIST_URL}}",
        },
        SessionSettings: {
          SessionName: "{{SERVER_NAME}}",
          Port: "{{PORT}}",
          QueryPort: "{{QUERY_PORT}}",
          MultiHome: "0.0.0.0",
        },
        "/Script/Engine.GameSession": {
          MaxPlayers: "{{MAX_PLAYERS}}",
        },
      },
      "ShooterGame/Saved/Config/LinuxServer/Game.ini": {
        __gsm_format: "ini",
        "/script/shootergame.shootergamemode": {
          MatingIntervalMultiplier: "{{MATING_INTERVAL_MULTIPLIER}}",
          EggHatchSpeedMultiplier: "{{EGG_HATCH_SPEED_MULTIPLIER}}",
          BabyMatureSpeedMultiplier: "{{BABY_MATURE_SPEED_MULTIPLIER}}",
          BabyFoodConsumptionSpeedMultiplier: "{{BABY_FOOD_CONSUMPTION_SPEED_MULTIPLIER}}",
          BabyImprintingStatScaleMultiplier: "{{BABY_IMPRINTING_STAT_SCALE_MULTIPLIER}}",
          bAllowAnyoneBabyImprintCuddle: "{{ALLOW_ANYONE_BABY_IMPRINT_CUDDLE}}",
          GlobalItemDecompositionTimeMultiplier: "{{GLOBAL_ITEM_DECOMPOSITION_TIME_MULTIPLIER}}",
          GlobalCorpseDecompositionTimeMultiplier: "{{GLOBAL_CORPSE_DECOMPOSITION_TIME_MULTIPLIER}}",
          SupplyCrateLootQualityMultiplier: "{{SUPPLY_CRATE_LOOT_QUALITY_MULTIPLIER}}",
          FishingLootQualityMultiplier: "{{FISHING_LOOT_QUALITY_MULTIPLIER}}",
          MaxNumberOfPlayersInTribe: "{{MAX_NUMBERS_OF_PLAYERS_IN_TRIBE}}",
          bAutoUnlockAllEngrams: "false",
          bDisableFriendlyFire: "{{PREVENT_FRIENDLY_FIRE}}",
          bPvEAllowStructuresAtSupplyDrops: "false",
          CropGrowthSpeedMultiplier: "{{CROP_GROWTH_SPEED_MULTIPLIER}}",
          CropDecaySpeedMultiplier: "{{CROP_DECAY_SPEED_MULTIPLIER}}",
          PersonalTamedDinosCap: "{{PERSONAL_TAMED_DINOS_CAP}}",
        },
      },
    },
  },
};
