import { V, group, STEAM_VARS, type GameTemplate } from "./types";
import { steamInstallScript } from "./steamcmd";

// Palworld packs every gameplay option into a single line:
//   [/Script/Pal.PalGameWorldSettings]
//   OptionSettings=(Difficulty=None,DayTimeSpeedRate=1.000000,...)
// The "palworld" config format serializer renders exactly that shape.
export const palworld: GameTemplate = {
  slug: "palworld",
  name: "Palworld",
  engine: "Unreal Engine 5",
  defaultPort: 8211,
  steamAppId: "2394010",
  iconEmoji: "🐾",
  supportsIpv6: false,
  category: "Survival",
  description: "Creature-collecting survival crafting",
  estimatedSize: "~8 GB",
  variables: [
    ...STEAM_VARS,

    ...group("Server", [
      V("Server Description", "SERVER_DESCRIPTION", "Description shown in the community server browser", "", { required: false }),
      V("Admin Password", "ADMIN_PASSWORD", "Password for admin commands — always set this", "", { required: false, type: "password" }),
      V("Server Password", "SERVER_PASSWORD", "Password required to join, empty = public", "", { required: false, type: "password" }),
      V("Public IP", "PUBLIC_IP", "Public IP advertised for crossplay, empty = auto-detect", "", { required: false }),
      V("Region", "REGION", "Region tag shown in the browser, empty = auto", "", { required: false }),
      V("Crossplay Platforms", "CROSSPLAY_PLATFORMS", "Platforms allowed to join", "Steam,Xbox,PS5,Mac", { required: false }),
      V("Use Auth", "USE_AUTH", "Authenticate players against the platform", "true", { required: false, type: "boolean" }),
      V("Ban List URL", "BAN_LIST_URL", "URL the server pulls its ban list from", "https://api.palworldgame.com/api/banlist.txt", { required: false }),
      V("Allow Client Mod", "ALLOW_CLIENT_MOD", "Permit modded clients to connect", "true", { required: false, type: "boolean" }),
      V("Show Player List", "SHOW_PLAYER_LIST", "Expose the player list to the server browser", "false", { required: false, type: "boolean" }),
      V("Coop Player Max", "COOP_PLAYER_MAX_NUM", "Player cap for co-op (non-dedicated) sessions", "4", {
        required: false, type: "number", min_value: 1, max_value: 32,
      }),
    ]),

    ...group("World Rates", [
      V("Difficulty", "DIFFICULTY", "Preset — anything except None overrides the individual multipliers", "None", {
        required: false, type: "select",
        enum_values: { None: "None (use custom values)", Casual: "Casual", Normal: "Normal", Hard: "Hard" },
      }),
      V("Day Time Speed", "DAY_TIME_SPEED_RATE", "Above 1 makes daytime pass faster", "1.000000", { required: false, type: "float", min_value: 0.1, max_value: 5 }),
      V("Night Time Speed", "NIGHT_TIME_SPEED_RATE", "Above 1 makes nighttime pass faster", "1.000000", { required: false, type: "float", min_value: 0.1, max_value: 5 }),
      V("EXP Rate", "EXP_RATE", "Experience multiplier (0.1-20)", "1.000000", { required: false, type: "float", min_value: 0.1, max_value: 20 }),
      V("Pal Capture Rate", "PAL_CAPTURE_RATE", "Capture success multiplier (0.5-2)", "1.000000", { required: false, type: "float", min_value: 0.5, max_value: 2 }),
      V("Pal Spawn Rate", "PAL_SPAWN_NUM_RATE", "Wild Pal density — heavy performance impact (0.5-3)", "1.000000", { required: false, type: "float", min_value: 0.5, max_value: 3 }),
      V("Work Speed Rate", "WORK_SPEED_RATE", "How fast Pals work at bases (0.5-5)", "1.000000", { required: false, type: "float", min_value: 0.1, max_value: 5 }),
      V("Egg Hatch Time", "PAL_EGG_DEFAULT_HATCHING_TIME", "Real hours for eggs to hatch", "1.000000", { required: false, type: "float", min_value: 0, max_value: 200 }),
      V("Collection Drop Rate", "COLLECTION_DROP_RATE", "Resource node yield multiplier", "1.000000", { required: false, type: "float", min_value: 0.1, max_value: 10 }),
      V("Collection Object HP", "COLLECTION_OBJECT_HP_RATE", "Resource node health — lower breaks faster", "1.000000", { required: false, type: "float", min_value: 0.1, max_value: 10 }),
      V("Collection Respawn Speed", "COLLECTION_OBJECT_RESPAWN_SPEED_RATE", "How fast harvested nodes respawn", "1.000000", { required: false, type: "float", min_value: 0.1, max_value: 10 }),
      V("Enemy Drop Rate", "ENEMY_DROP_ITEM_RATE", "Loot dropped by defeated enemies", "1.000000", { required: false, type: "float", min_value: 0.1, max_value: 10 }),
      V("Monster Farm Speed", "MONSTER_FARM_ACTION_SPEED_RATE", "Ranch production speed", "1.000000", { required: false, type: "float", min_value: 0.1, max_value: 10 }),
      V("Auto Save Span", "AUTO_SAVE_SPAN", "Seconds between world saves", "30.000000", { required: false, type: "float", min_value: 10, max_value: 3600 }),
    ]),

    ...group("Combat & Damage", [
      V("Pal Damage Attack", "PAL_DAMAGE_RATE_ATTACK", "Damage Pals deal (0.1-5)", "1.000000", { required: false, type: "float", min_value: 0.1, max_value: 5 }),
      V("Pal Damage Defense", "PAL_DAMAGE_RATE_DEFENSE", "Damage Pals take (0.1-5)", "1.000000", { required: false, type: "float", min_value: 0.1, max_value: 5 }),
      V("Player Damage Attack", "PLAYER_DAMAGE_RATE_ATTACK", "Damage players deal (0.1-5)", "1.000000", { required: false, type: "float", min_value: 0.1, max_value: 5 }),
      V("Player Damage Defense", "PLAYER_DAMAGE_RATE_DEFENSE", "Damage players take (0.1-5)", "1.000000", { required: false, type: "float", min_value: 0.1, max_value: 5 }),
      V("Death Penalty", "DEATH_PENALTY", "What players drop on death", "Item", {
        required: false, type: "select",
        enum_values: {
          None: "None — keep everything", Item: "Item — drop items, keep gear",
          ItemAndEquipment: "Item and Equipment", All: "All — also drop carried Pals",
        },
      }),
      V("Player to Player Damage", "ENABLE_PLAYER_TO_PLAYER_DAMAGE", "Master PvP switch", "false", { required: false, type: "boolean" }),
      V("Friendly Fire", "ENABLE_FRIENDLY_FIRE", "Guild members can damage each other", "false", { required: false, type: "boolean" }),
      V("Is PvP", "IS_PVP", "Flag the server as PvP in the browser", "false", { required: false, type: "boolean" }),
      V("Invader Enemy", "ENABLE_INVADER_ENEMY", "Enable base raid events", "true", { required: false, type: "boolean" }),
      V("Hardcore", "HARDCORE", "Permadeath — players lose everything on death", "false", { required: false, type: "boolean" }),
      V("Pal Lost", "PAL_LOST", "Pals are permanently lost when the player dies", "false", { required: false, type: "boolean" }),
      V("Predator Boss Pal", "ENABLE_PREDATOR_BOSS_PAL", "Spawn predator boss Pals in the world", "true", { required: false, type: "boolean" }),
      V("Aim Assist (Pad)", "ENABLE_AIM_ASSIST_PAD", "Allow controller aim assist", "true", { required: false, type: "boolean" }),
      V("Aim Assist (Keyboard)", "ENABLE_AIM_ASSIST_KEYBOARD", "Allow keyboard/mouse aim assist", "false", { required: false, type: "boolean" }),
    ]),

    ...group("Survival Rates", [
      V("Player Stomach Decrease", "PLAYER_STOMACH_DECREACE_RATE", "How fast players get hungry", "1.000000", { required: false, type: "float", min_value: 0.1, max_value: 5 }),
      V("Player Stamina Decrease", "PLAYER_STAMINA_DECREACE_RATE", "How fast players burn stamina", "1.000000", { required: false, type: "float", min_value: 0.1, max_value: 5 }),
      V("Player HP Regen", "PLAYER_AUTO_HP_REGENE_RATE", "Out-of-combat player healing rate", "1.000000", { required: false, type: "float", min_value: 0.1, max_value: 10 }),
      V("Player HP Regen (Sleep)", "PLAYER_AUTO_HP_REGENE_RATE_IN_SLEEP", "Player healing rate while sleeping", "1.000000", { required: false, type: "float", min_value: 0.1, max_value: 10 }),
      V("Pal Stomach Decrease", "PAL_STOMACH_DECREACE_RATE", "How fast Pals get hungry", "1.000000", { required: false, type: "float", min_value: 0.1, max_value: 5 }),
      V("Pal Stamina Decrease", "PAL_STAMINA_DECREACE_RATE", "How fast Pals burn stamina", "1.000000", { required: false, type: "float", min_value: 0.1, max_value: 5 }),
      V("Pal HP Regen", "PAL_AUTO_HP_REGENE_RATE", "Out-of-combat Pal healing rate", "1.000000", { required: false, type: "float", min_value: 0.1, max_value: 10 }),
      V("Pal HP Regen (Sleep)", "PAL_AUTO_HP_REGENE_RATE_IN_SLEEP", "Pal healing rate while resting", "1.000000", { required: false, type: "float", min_value: 0.1, max_value: 10 }),
      V("Item Weight Rate", "ITEM_WEIGHT_RATE", "Item weight multiplier — lower lets players carry more", "1.000000", { required: false, type: "float", min_value: 0.1, max_value: 10 }),
      V("Equipment Durability Damage", "EQUIPMENT_DURABILITY_DAMAGE_RATE", "How fast equipment wears out, 0 = never", "1.000000", { required: false, type: "float", min_value: 0, max_value: 10 }),
      V("Non-Login Penalty", "ENABLE_NON_LOGIN_PENALTY", "Apply penalties to players who stop logging in", "true", { required: false, type: "boolean" }),
    ]),

    ...group("Base & Building", [
      V("Base Camp Max", "BASE_CAMP_MAX_NUM", "Total base camps server-wide", "128", {
        required: false, type: "number", min_value: 1, max_value: 1000,
      }),
      V("Base Camp Workers", "BASE_CAMP_WORKER_MAX_NUM", "Pals working at a single base (max 50)", "15", {
        required: false, type: "number", min_value: 1, max_value: 50,
      }),
      V("Bases Per Guild", "BASE_CAMP_MAX_NUM_IN_GUILD", "Base camps each guild may own (max 10)", "4", {
        required: false, type: "number", min_value: 1, max_value: 10,
      }),
      V("Max Building Limit", "MAX_BUILDING_LIMIT_NUM", "Server-wide building piece cap, 0 = unlimited", "0", {
        required: false, type: "number", min_value: 0, max_value: 1000000,
      }),
      V("Build Object HP", "BUILD_OBJECT_HP_RATE", "Structure health multiplier", "1.000000", { required: false, type: "float", min_value: 0.1, max_value: 10 }),
      V("Build Object Damage", "BUILD_OBJECT_DAMAGE_RATE", "Damage dealt to structures", "1.000000", { required: false, type: "float", min_value: 0.1, max_value: 10 }),
      V("Build Deterioration", "BUILD_OBJECT_DETERIORATION_DAMAGE_RATE", "Structure decay rate, 0 = no decay", "1.000000", { required: false, type: "float", min_value: 0, max_value: 10 }),
      V("Build Area Limit", "BUILD_AREA_LIMIT", "Restrict building to base camp areas", "false", { required: false, type: "boolean" }),
      V("Defense Other Guild Player", "ENABLE_DEFENSE_OTHER_GUILD_PLAYER", "Base defences target other guilds' players", "false", { required: false, type: "boolean" }),
      V("Invisible Other Guild Base FX", "INVISIBLE_OTHER_GUILD_BASE_CAMP_AREA_FX", "Hide other guilds' base area effects", "false", { required: false, type: "boolean" }),
    ]),

    ...group("Guild & Players", [
      V("Guild Player Max", "GUILD_PLAYER_MAX_NUM", "Players allowed per guild", "20", {
        required: false, type: "number", min_value: 1, max_value: 100,
      }),
      V("Auto Reset Guild", "AUTO_RESET_GUILD_NO_ONLINE_PLAYERS", "Reset guilds with no online players", "false", { required: false, type: "boolean" }),
      V("Auto Reset Guild Time", "AUTO_RESET_GUILD_TIME_NO_ONLINE_PLAYERS", "Hours offline before a guild resets", "72.000000", { required: false, type: "float", min_value: 1, max_value: 8760 }),
      V("Guild Rejoin Cooldown", "GUILD_REJOIN_COOLDOWN_MINUTES", "Minutes before a player may rejoin a guild", "0", {
        required: false, type: "number", min_value: 0, max_value: 10080,
      }),
      V("Fast Travel", "ENABLE_FAST_TRAVEL", "Allow fast travel between statues", "true", { required: false, type: "boolean" }),
      V("Fast Travel Base Camp Only", "ENABLE_FAST_TRAVEL_ONLY_BASE_CAMP", "Restrict fast travel to base camps", "false", { required: false, type: "boolean" }),
      V("Start Location By Map", "IS_START_LOCATION_SELECT_BY_MAP", "Let players pick their spawn on the map", "true", { required: false, type: "boolean" }),
      V("Exist Player After Logout", "EXIST_PLAYER_AFTER_LOGOUT", "Player bodies persist in the world after logout", "false", { required: false, type: "boolean" }),
      V("Pickup Other Guild Death Drop", "CAN_PICKUP_OTHER_GUILD_DEATH_PENALTY_DROP", "Other guilds may loot death drops", "false", { required: false, type: "boolean" }),
      V("Chat Post Limit", "CHAT_POST_LIMIT_PER_MINUTE", "Chat messages allowed per minute", "30", {
        required: false, type: "number", min_value: 1, max_value: 1000,
      }),
      V("Drop Item Max", "DROP_ITEM_MAX_NUM", "Items allowed on the ground before deletion", "3000", {
        required: false, type: "number", min_value: 100, max_value: 20000,
      }),
      V("Drop Item Alive Hours", "DROP_ITEM_ALIVE_MAX_HOURS", "Hours dropped items persist", "1.000000", { required: false, type: "float", min_value: 0.1, max_value: 24 }),
      V("Supply Drop Span", "SUPPLY_DROP_SPAN", "Minutes between supply drops", "180", {
        required: false, type: "number", min_value: 0, max_value: 1440,
      }),
    ]),

    ...group("Stat Enhancement", [
      V("Enhance Health", "ALLOW_ENHANCE_STAT_HEALTH", "Players may spend points on Health", "true", { required: false, type: "boolean" }),
      V("Enhance Attack", "ALLOW_ENHANCE_STAT_ATTACK", "Players may spend points on Attack", "true", { required: false, type: "boolean" }),
      V("Enhance Stamina", "ALLOW_ENHANCE_STAT_STAMINA", "Players may spend points on Stamina", "true", { required: false, type: "boolean" }),
      V("Enhance Weight", "ALLOW_ENHANCE_STAT_WEIGHT", "Players may spend points on Weight", "true", { required: false, type: "boolean" }),
      V("Enhance Work Speed", "ALLOW_ENHANCE_STAT_WORKSPEED", "Players may spend points on Work Speed", "true", { required: false, type: "boolean" }),
      V("Deny Technology List", "DENY_TECHNOLOGY_LIST", "Comma-separated technologies players cannot unlock", "", { required: false }),
    ]),

    ...group("RCON & REST API", [
      V("RCON Enabled", "RCON_ENABLED", "Enable the RCON listener", "false", { required: false, type: "boolean" }),
      V("RCON Port", "RCON_PORT", "Port RCON binds to", "25575", {
        required: false, type: "number", min_value: 1, max_value: 65535,
      }),
      V("REST API Enabled", "REST_API_ENABLED", "Enable the HTTP REST admin API", "false", { required: false, type: "boolean" }),
      V("REST API Port", "REST_API_PORT", "Port the REST API binds to", "8212", {
        required: false, type: "number", min_value: 1, max_value: 65535,
      }),
      V("Log Format Type", "LOG_FORMAT_TYPE", "Server log output format", "Text", {
        required: false, type: "select", enum_values: { Text: "Text", Json: "JSON" },
      }),
      V("Backup Save Data", "IS_USE_BACKUP_SAVE_DATA", "Keep rotating backups of the save", "true", { required: false, type: "boolean" }),
      V("Show Join/Left Message", "IS_SHOW_JOIN_LEFT_MESSAGE", "Announce joins and disconnects in chat", "true", { required: false, type: "boolean" }),
      V("Voice Chat", "ENABLE_VOICE_CHAT", "Enable in-game proximity voice chat", "false", { required: false, type: "boolean" }),
    ]),
  ],

  installScript: steamInstallScript({
    appId: "2394010",
    name: "Palworld",
    post: `## Palworld reads PalWorldSettings.ini from the Saved config directory
mkdir -p "$INSTALL_DIR/Pal/Saved/Config/LinuxServer"`,
  }),

  startCommand: `cd {{INSTALL_PATH}} && ./PalServer.sh -port={{PORT}} -queryport={{QUERY_PORT}} -players={{MAX_PLAYERS}} -useperfthreads -NoAsyncLoadingThread -UseMultithreadForDS`,
  stopCommand: null,
  configFiles: { "Pal/Saved/Config/LinuxServer/PalWorldSettings.ini": "PalWorldSettings.ini" },
  defaultConfig: {
    __gsm_format: "palworld",
    Difficulty: "{{DIFFICULTY}}",
    RandomizerType: "None",
    RandomizerSeed: "",
    bIsRandomizerPalLevelRandom: "false",
    DayTimeSpeedRate: "{{DAY_TIME_SPEED_RATE}}",
    NightTimeSpeedRate: "{{NIGHT_TIME_SPEED_RATE}}",
    ExpRate: "{{EXP_RATE}}",
    PalCaptureRate: "{{PAL_CAPTURE_RATE}}",
    PalSpawnNumRate: "{{PAL_SPAWN_NUM_RATE}}",
    PalDamageRateAttack: "{{PAL_DAMAGE_RATE_ATTACK}}",
    PalDamageRateDefense: "{{PAL_DAMAGE_RATE_DEFENSE}}",
    PlayerDamageRateAttack: "{{PLAYER_DAMAGE_RATE_ATTACK}}",
    PlayerDamageRateDefense: "{{PLAYER_DAMAGE_RATE_DEFENSE}}",
    PlayerStomachDecreaceRate: "{{PLAYER_STOMACH_DECREACE_RATE}}",
    PlayerStaminaDecreaceRate: "{{PLAYER_STAMINA_DECREACE_RATE}}",
    PlayerAutoHPRegeneRate: "{{PLAYER_AUTO_HP_REGENE_RATE}}",
    PlayerAutoHpRegeneRateInSleep: "{{PLAYER_AUTO_HP_REGENE_RATE_IN_SLEEP}}",
    PalStomachDecreaceRate: "{{PAL_STOMACH_DECREACE_RATE}}",
    PalStaminaDecreaceRate: "{{PAL_STAMINA_DECREACE_RATE}}",
    PalAutoHPRegeneRate: "{{PAL_AUTO_HP_REGENE_RATE}}",
    PalAutoHpRegeneRateInSleep: "{{PAL_AUTO_HP_REGENE_RATE_IN_SLEEP}}",
    BuildObjectHpRate: "{{BUILD_OBJECT_HP_RATE}}",
    BuildObjectDamageRate: "{{BUILD_OBJECT_DAMAGE_RATE}}",
    BuildObjectDeteriorationDamageRate: "{{BUILD_OBJECT_DETERIORATION_DAMAGE_RATE}}",
    CollectionDropRate: "{{COLLECTION_DROP_RATE}}",
    CollectionObjectHpRate: "{{COLLECTION_OBJECT_HP_RATE}}",
    CollectionObjectRespawnSpeedRate: "{{COLLECTION_OBJECT_RESPAWN_SPEED_RATE}}",
    EnemyDropItemRate: "{{ENEMY_DROP_ITEM_RATE}}",
    DeathPenalty: "{{DEATH_PENALTY}}",
    bEnablePlayerToPlayerDamage: "{{ENABLE_PLAYER_TO_PLAYER_DAMAGE}}",
    bEnableFriendlyFire: "{{ENABLE_FRIENDLY_FIRE}}",
    bEnableInvaderEnemy: "{{ENABLE_INVADER_ENEMY}}",
    bActiveUNKO: "false",
    bEnableAimAssistPad: "{{ENABLE_AIM_ASSIST_PAD}}",
    bEnableAimAssistKeyboard: "{{ENABLE_AIM_ASSIST_KEYBOARD}}",
    DropItemMaxNum: "{{DROP_ITEM_MAX_NUM}}",
    DropItemMaxNum_UNKO: "100",
    BaseCampMaxNum: "{{BASE_CAMP_MAX_NUM}}",
    BaseCampWorkerMaxNum: "{{BASE_CAMP_WORKER_MAX_NUM}}",
    DropItemAliveMaxHours: "{{DROP_ITEM_ALIVE_MAX_HOURS}}",
    bAutoResetGuildNoOnlinePlayers: "{{AUTO_RESET_GUILD_NO_ONLINE_PLAYERS}}",
    AutoResetGuildTimeNoOnlinePlayers: "{{AUTO_RESET_GUILD_TIME_NO_ONLINE_PLAYERS}}",
    GuildPlayerMaxNum: "{{GUILD_PLAYER_MAX_NUM}}",
    BaseCampMaxNumInGuild: "{{BASE_CAMP_MAX_NUM_IN_GUILD}}",
    PalEggDefaultHatchingTime: "{{PAL_EGG_DEFAULT_HATCHING_TIME}}",
    WorkSpeedRate: "{{WORK_SPEED_RATE}}",
    AutoSaveSpan: "{{AUTO_SAVE_SPAN}}",
    bIsMultiplay: "false",
    bIsPvP: "{{IS_PVP}}",
    bHardcore: "{{HARDCORE}}",
    bPalLost: "{{PAL_LOST}}",
    bCharacterRecreateInHardcore: "false",
    bCanPickupOtherGuildDeathPenaltyDrop: "{{CAN_PICKUP_OTHER_GUILD_DEATH_PENALTY_DROP}}",
    bEnableNonLoginPenalty: "{{ENABLE_NON_LOGIN_PENALTY}}",
    bEnableFastTravel: "{{ENABLE_FAST_TRAVEL}}",
    bEnableFastTravelOnlyBaseCamp: "{{ENABLE_FAST_TRAVEL_ONLY_BASE_CAMP}}",
    bIsStartLocationSelectByMap: "{{IS_START_LOCATION_SELECT_BY_MAP}}",
    bExistPlayerAfterLogout: "{{EXIST_PLAYER_AFTER_LOGOUT}}",
    bEnableDefenseOtherGuildPlayer: "{{ENABLE_DEFENSE_OTHER_GUILD_PLAYER}}",
    bInvisibleOtherGuildBaseCampAreaFX: "{{INVISIBLE_OTHER_GUILD_BASE_CAMP_AREA_FX}}",
    bBuildAreaLimit: "{{BUILD_AREA_LIMIT}}",
    ItemWeightRate: "{{ITEM_WEIGHT_RATE}}",
    CoopPlayerMaxNum: "{{COOP_PLAYER_MAX_NUM}}",
    ServerPlayerMaxNum: "{{MAX_PLAYERS}}",
    ServerName: "{{SERVER_NAME}}",
    ServerDescription: "{{SERVER_DESCRIPTION}}",
    AdminPassword: "{{ADMIN_PASSWORD}}",
    ServerPassword: "{{SERVER_PASSWORD}}",
    bAllowClientMod: "{{ALLOW_CLIENT_MOD}}",
    PublicPort: "{{PORT}}",
    PublicIP: "{{PUBLIC_IP}}",
    RCONEnabled: "{{RCON_ENABLED}}",
    RCONPort: "{{RCON_PORT}}",
    Region: "{{REGION}}",
    bUseAuth: "{{USE_AUTH}}",
    BanListURL: "{{BAN_LIST_URL}}",
    RESTAPIEnabled: "{{REST_API_ENABLED}}",
    RESTAPIPort: "{{REST_API_PORT}}",
    bShowPlayerList: "{{SHOW_PLAYER_LIST}}",
    ChatPostLimitPerMinute: "{{CHAT_POST_LIMIT_PER_MINUTE}}",
    CrossplayPlatforms: "({{CROSSPLAY_PLATFORMS}})",
    bIsUseBackupSaveData: "{{IS_USE_BACKUP_SAVE_DATA}}",
    LogFormatType: "{{LOG_FORMAT_TYPE}}",
    bIsShowJoinLeftMessage: "{{IS_SHOW_JOIN_LEFT_MESSAGE}}",
    SupplyDropSpan: "{{SUPPLY_DROP_SPAN}}",
    EnablePredatorBossPal: "{{ENABLE_PREDATOR_BOSS_PAL}}",
    MaxBuildingLimitNum: "{{MAX_BUILDING_LIMIT_NUM}}",
    ServerReplicatePawnCullDistance: "15000.000000",
    bAllowGlobalPalboxExport: "true",
    bAllowGlobalPalboxImport: "false",
    EquipmentDurabilityDamageRate: "{{EQUIPMENT_DURABILITY_DAMAGE_RATE}}",
    ItemContainerForceMarkDirtyInterval: "1.000000",
    MonsterFarmActionSpeedRate: "{{MONSTER_FARM_ACTION_SPEED_RATE}}",
    DenyTechnologyList: "{{DENY_TECHNOLOGY_LIST}}",
    GuildRejoinCooldownMinutes: "{{GUILD_REJOIN_COOLDOWN_MINUTES}}",
    bEnableVoiceChat: "{{ENABLE_VOICE_CHAT}}",
    bAllowEnhanceStat_Health: "{{ALLOW_ENHANCE_STAT_HEALTH}}",
    bAllowEnhanceStat_Attack: "{{ALLOW_ENHANCE_STAT_ATTACK}}",
    bAllowEnhanceStat_Stamina: "{{ALLOW_ENHANCE_STAT_STAMINA}}",
    bAllowEnhanceStat_Weight: "{{ALLOW_ENHANCE_STAT_WEIGHT}}",
    bAllowEnhanceStat_WorkSpeed: "{{ALLOW_ENHANCE_STAT_WORKSPEED}}",
  },
};
